### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by monperrus** [iradicek/clara#2]
trying to build, I obtain `error adding symbols: Bad value`

```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/clara/pylpsolve.o -llpsolve55 -o build/lib.linux-x86_64-2.7/clara/pylpsolve.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblpsolve55.a(lp_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblpsolve55.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
any idea?

**Comment by iradicek** [comment]
Which OS/distribution are you trying to build on? I can try and see where the issue is. So far, I have built it on Fedora/RHEL.

**Comment by iradicek** [comment]
I have reproduced the issue on Debian. It seems that the needed package is 'lp-solve' (it contains the dynamic version of the library). I have also modified 'setup.py' script to find this library.

However, since the library is in a "non-default" place, the following is required before running the tool:
`export LD_LIBRARY_PATH=/usr/lib/lp_solve/`

If this works for you now, I will also add it to the README.

**Comment by monperrus** [comment]
I can build and run the example now on my Debian box. Thanks.

**Comment by iradicek** [comment]
I have also updated and extended your clarifications for the installation with this. Thanks for the clarifications.

**Comment by hadisfr** [comment]
@iradicek Would you mind adding some notes about `export LD_LIBRARY_PATH=/usr/lib/lp_solve/` to _Installation & running_ part of _README_?

**Comment by iradicek** [comment]
@hadisfr - are you able to build now?

**Comment by hadisfr** [comment]
@iradicek Yes, I'm able to build and run the examples. Thank you.
