### ISSUE TITLE
Boolean constants are unsupported

### ISSUE THREAD

**Issue by xjr01** [iradicek/clara#26]
I'm using Clara to cluster a group of code submissions but it failed with an error message(without showing on which code it failed):
```
Error occured: Unimplemented visitor: 'NameConstant' (False)
```
It took me quite a long time to realize that Clara can't process programs that contain boolean constants `True` or `False`. However, `True` and `False` appear quite often in a program.
Besides, I would really appreciate it if you can just skip the failed samples and report the error messages showing WHICH code it failed to process.

**Comment by ullash21** [comment]
I am facing a very similar issue with `None` keyword. 

@xjr01 did you manage to find a fix?


```Error occured: Unimplemented visitor: 'NameConstant' (None)```

**Comment by xjr01** [comment]
> I am facing a very similar issue with `None` keyword.
> 
> @xjr01 did you manage to find a fix?
> 
> `Error occured: Unimplemented visitor: 'NameConstant' (None)`

Well, this doesn't seem like a bug. It's simply because they haven't considered these constants.

So I guess there's no way to fix it unless you become a developer. Right now you might have to remove the codes that contain these constants.

**Comment by ullash21** [comment]
Thank you for the feedback. I will try to do that.

**Comment by iradicek** [comment]
Hi. Sorry for not looking into this sooner. It seems that these are leftover problems from migrating Python 2 -> Python 3, which was never fully tested. I'm looking into the easiest way to fix this.

**Comment by iradicek** [comment]
Can you please check whether branch `upgrade-python-versions` in #27 fixes your issues. If it still doesn't work, can you please send me the Python file where you face the issues?

**Comment by ullash21** [comment]
Hi, Yes, it does for me. Thank you.

**Comment by iradicek** [comment]
OK. I will merge this PR and close this issue. If there are any leftover bugs left, please do create another issue.
