### ISSUE TITLE
Cannot find function in C programs

### ISSUE THREAD

**Issue by JialuZhang** [iradicek/clara#30]
Error occured: Unknown function: 'main'

Here is the issue.

$ cat examples/example.c
#include<stdio.h>

int main(){
  int n, temp;
  scanf("%d", &n);
  
  temp = n;
  printf ("%d",temp);
  return 0;
}

$ cat examples/example2.c 
#include<stdio.h>

int main(){
  int n;
  scanf("%d", &n);

  printf("%d", n);
  return 0;
}

$ clara match examples/example.c examples/example2.c --entryfnc "main" --ins "[[3]]"
Error occured: Unknown function: 'main'

$ clara match examples/example.c examples/example2.c --entryfnc main --args "[[3]]"
Error occured: Unknown function: 'main'

I cannot find anyway to let Clara find the function "main" in C programs. Any help will be appreciated.

**Comment by JialuZhang** [comment]
Python examples from documentation work very well.

Cannot find function in C programs.

**Comment by iradicek** [comment]
I'm not able to reproduce your issue. I get the following:

```
$ clara match examples/example.c examples/example2.c --entryfnc "main" --ins "[[3]]" --verbose 1
[debug] Guessed language: c
[debug] Reading and parsing source file 'examples/example.c'
[debug] Reading and parsing source file 'examples/example2.c'
[debug] Programs executed, matching traces
[debug] Not bijective - different number of variables
No match!
```

and

```
$ clara match examples/example.c examples/example2.c --entryfnc main --args "[[3]]"
Error occured: Wrong number of args: expected 0, got 1
```
Note that this is the expected output. Can you paste output of commands `clara model examples/example.c` and `clara model examples/example2.c`.

**Comment by JialuZhang** [comment]
Thank you very much. Here is the output.

$ clara model examples/example.c --verbose 1
```
[debug] Guessed language: c
[debug] Reading and parsing source file 'examples/example.c'

```
$ clara model examples/example2.c --verbose 1
```
[debug] Guessed language: c
[debug] Reading and parsing source file 'examples/example2.c'

```
I am also trying the file in the "examples" folder. Running "clara model examples/c/hello_world.c" does not have any output. However, running "clara model examples/c1.py" does have outputs.

$ clara model examples/c/hello_world.c 

$ clara model examples/c1.py 
```
fun computeDeriv (poly: *) : *
---------------------------------------------------------------------
poly : *, result : *, e : *, iter#0 : *, ind#0 : int

Loc 1 (around the beginning of function 'computeDeriv')
---------------------------------------
  result := ListInit()
  iter#0 := range(1, len(poly))
  ind#0 := 0
---------------------------------------
  True -> 2   False -> None

Loc 2 (the condition of the 'for' loop at line 3)
---------------------------------------
  $cond := Lt(ind#0, len(iter#0))
---------------------------------------
  True -> 4   False -> 3

Loc 3 (*after* the 'for' loop starting at line 3)
---------------------------------------
  $ret := ite(Eq(result, ListInit()), ListInit(0.0), result)
---------------------------------------
  True -> None   False -> None

Loc 4 (inside the body of the 'for' loop beginning at line 4)
---------------------------------------
  e := GetElement(iter#0, ind#0)
  ind#0 := Add(ind#0, 1)
  result := append(result, float(Mult(GetElement(poly, e'), e')))
---------------------------------------
  True -> 2   False -> None
```

**Comment by JialuZhang** [comment]
One thing that maybe is worth mentioning here is that I am running the experiments on my mac. After installing lpsolve via Homebrew, when I typed "make" in clara folder, I got the following error. 
```
    /usr/local/include/pthread.h:540:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
    /usr/local/include/pthread.h:200:34: note: expanded from macro '_PTHREAD_SWIFT_IMPORTER_NULLABILITY_COMPAT'
            defined(SWIFT_CLASS_EXTRA) && (!defined(SWIFT_SDK_OVERLAY_PTHREAD_EPOCH) || (SWIFT_SDK_OVERLAY_PTHREAD_EPOCH < 1))
                                            ^
    clara/pylpsolve.c:630:10: fatal error: 'lpsolve/lp_lib.h' file not found
    #include "lpsolve/lp_lib.h"
             ^~~~~~~~~~~~~~~~~~
    194 warnings and 1 error generated.
    error: command 'clang' failed with exit status 1
```
I changed the line 630 in file clara/pylpsolve.c from #include "lpsolve/lp_lib.h" to #include <lp_lib.h> and then I am able to finish the installation process. 
I was also wondering if this change makes the C programs not working in clara. 

But what is still weird is that python programs are still working very well, only C programs are not working. :) Many thanks.

**Comment by iradicek** [comment]
The error about lpsolve should not be relevant to the above problems, but it might create problems around repair itself (not clustering).

However, it seems that there is some problem with C parser, because it's not reading C programs at all - they appear to be empty. The best advice I can give is to try it on a Linux system (Fedora or Debian are tested).

**Comment by JialuZhang** [comment]
@iradicek  Will do! Thank you for your clarification and assistance. They are very helpful.

**Comment by JialuZhang** [comment]
I closed this issue. Clara runs in my ubuntu virtual machine very smoothly.
